version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: epam
    environment:
      - POSTGRES_DB=gym_crm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - activemq_data:/opt/activemq/data


volumes:
  db_data:
  activemq_data: