spring.profiles.active=local

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger - %msg%n

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

jwt.expiration=3600000
jwt.secret=b85795fb550cb9b671c6a7abed6d3285d8023e66ab1ad2698ab19dfc8b3c5c70