spring.profiles.active=local
spring.application.name=gym-service
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger - %msg%n
eureka.client.service-url.defaultZone= http://localhost:8761/eureka

resilience4j.circuitbreaker.instances.trainer-workload.slidingWindowSize=10
resilience4j.circuitbreaker.instances.trainer-workload.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.trainer-workload.failureRateThreshold=50
resilience4j.circuitbreaker.instances.trainer-workload.waitDurationInOpenState=30s

resilience4j.retry.instances.trainer-workload.max-attempts=3
resilience4j.retry.instances.trainer-workload.wait-duration=1s

spring.cloud.openfeign.client.config.trainer-workload-service.connectTimeout=3000
spring.cloud.openfeign.client.config.trainer-workload-service.readTimeout=5000

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

jwt.expiration=3600000
jwt.secret=b85795fb550cb9b671c6a7abed6d3285d8023e66ab1ad2698ab19dfc8b3c5c70