spring.profiles.active=local

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger - %msg%n

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always