spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm_stg
spring.datasource.username=stg
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
