spring:
  application:
    name: trainer-workload-service
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27017/trainer-workload-db?authSource=admin&authMechanism=SCRAM-SHA-256
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: b85795fb550cb9b671c6a7abed6d3285d8023e66ab1ad2698ab19dfc8b3c5c70